version: '3.9'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - redis
      - postgres-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/test_db
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
  postgres-db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=test_db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    ports:
      - "5432:5432"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"