version: '3.9'
services:
  postgres-db:
    image: postgres:16.1
    environment:
      - POSTGRES_DB=test_db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    ports:
      - "5432:5432"

  redis:
    image: redis:7.0.12
    ports:
      - "6379:6379"